name: Build Tiny11 Windows

on:
  workflow_dispatch:

jobs:
  build-tiny11:
    runs-on: windows-latest
    timeout-minutes: 180
    env:
      BUILD_VERSION: "22631.2861"
      BUILD_LANG: "en-us"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup Build Environment
      shell: powershell
      run: |
        # Buat folder 25h2 jika belum ada
        New-Item -ItemType Directory -Path ".\25h2" -Force
        
        # Buat file input untuk UUP Dump
        $inputContent = "$env:BUILD_VERSION`n$env:BUILD_LANG"
        Set-Content -Path ".\25h2\input.txt" -Value $inputContent
        
        # Set execution policy
        Set-ExecutionPolicy Bypass -Scope Process -Force

    - name: Download UUP Dump ISO
      shell: powershell
      working-directory: ./25h2
      run: |
        # Tampilkan isi input.txt
        Write-Host "Isi input.txt:"
        Get-Content input.txt
        
        # Jalankan script UUP
        Write-Host "Memulai download Windows ISO..."
        $output = cmd /c 'uup_download_windows.cmd < input.txt' 2>&1 | Out-String
        Write-Host $output
        
        # Cari ISO di dalam folder 25h2 (dan subfolder) saja
        $iso = Get-ChildItem -Path . -Recurse -Include *.iso, *.ISO | Select-Object -First 1
        if ($iso) {
            Write-Host "✅ ISO ditemukan di: $($iso.FullName)"
            # Simpan path ISO ke environment variable untuk langkah selanjutnya
            echo "ISO_PATH=$($iso.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append
        } else {
            Write-Error "❌ ISO tidak ditemukan setelah proses download di dalam folder 25h2"
            Write-Host "Struktur folder 25h2:"
            Get-ChildItem -Path . -Recurse | Format-Table FullName
            exit 1
        }
      env:
        _NO_HTTP_PROXY: 1
        _RETRY_DOWNLOAD: 1

    - name: Install Dependencies
      shell: powershell
      run: |
        # Install modul PowerShell
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
        Install-Module -Name 7Zip4Powershell -Force -Scope CurrentUser -AllowClobber
        Install-Module -Name VHD -Force -Scope CurrentUser -AcceptLicense

    - name: Run Tiny11 Builder
      shell: powershell
      run: |
        Write-Host "Menggunakan ISO: $env:ISO_PATH"
        .\tiny11Coremaker.ps1 -IsoPath "$env:ISO_PATH" `
          -SkipIntegrityCheck `
          -RemoveTeams `
          -RemoveEdge `
          -RemoveOneDrive `
          -Verbose
        
        # Verifikasi output
        $outputIso = Get-ChildItem -Path . -Filter "tiny11-*.iso" | Select-Object -First 1
        if (-not $outputIso) {
            throw "❌ Build failed! No output ISO found"
        }
        Write-Host "✅ Build berhasil: $($outputIso.FullName)"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tiny11-image
        path: |
          tiny11-*.iso
          .\output\*
        retention-days: 1
