name: Build Tiny11 Windows

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-tiny11:
    runs-on: windows-latest
    timeout-minutes: 120  # Waktu eksekusi maksimum

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download UUP Dump ISO
      shell: cmd
      working-directory: ./25h2
      run: |
        uup_download_windows.cmd < input.txt
      env:
        _NO_HTTP_PROXY: 1  # Optional: Untuk masalah proxy
      continue-on-error: false

    - name: Setup Build Environment
      shell: powershell
      run: |
        # Buat file input otomatis untuk UUP Dump
        Set-Content -Path .\25h2\input.txt -Value "22631.2861`nen-us"
        
        # Temukan file ISO yang diunduh
        $isoFile = Get-ChildItem -Path .\25h2 -Filter *.iso | Select-Object -First 1
        if (-not $isoFile) {
            Write-Error "ISO file not found!"
            exit 1
        }
        echo "ISO_PATH=$($isoFile.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Install Dependencies
      shell: powershell
      run: |
        # Install modul PowerShell yang diperlukan
        Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
        Install-Module -Name 7Zip4Powershell -Force -Scope CurrentUser -AllowClobber
        Install-Module -Name VHD -Force -Scope CurrentUser

    - name: Run Tiny11 Builder
      shell: powershell
      run: |
        .\tiny11Coremaker.ps1 -IsoPath "$env:ISO_PATH" -SkipIntegrityCheck -RemoveTeams -RemoveEdge -RemoveOneDrive

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: tiny11-image
        path: |
          tiny11-*.iso
          .\output\*
        retention-days: 1
