name: Build Tiny11 ISO

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Clone tiny11builder repo
        run: |
          git clone https://github.com/pitekkate/tiny11builder.git 

      - name: Install tiny11builder dependencies
        working-directory: tiny11builder
        run: |
          pip install -r requirements.txt

      - name: Run tiny11builder
        working-directory: tiny11builder
        run: |
          python builder.py

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tiny11-iso
          path: tiny11builder/output/*.iso
